services:
  order_service:
    build: .
    ports:
      - "5001:5001"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database-2-instance-1.c5cssq6sys87.us-east-2.rds.amazonaws.com:3306/order_service
      - SPRING_DATASOURCE_USERNAME=database2
      - SPRING_DATASOURCE_PASSWORD=database2